name: แจ้งเตือน Discord เมื่อมีการ Push

on:
  push:
    branches:
      - '**'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: ส่ง Commit ไป Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          # -------------------------------
          # เก็บค่าข้อมูลพื้นฐานของ Push
          # -------------------------------
          REPO="${{ github.repository }}"          # repo ที่ถูก push (เช่น user/myrepo)
          BRANCH="${{ github.ref_name }}"          # branch ที่ถูก push (เช่น main)
          AUTHOR="${{ github.actor }}"             # คนที่ push
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)   # commit id ย่อ

          # -------------------------------
          # ดึง commit messages ทั้งหมดที่อยู่ใน push
          # -------------------------------
          COMMITS=$(echo '${{ toJson(github.event.commits) }}' \
            | jq -r '.[] | "- [" + .id[0:7] + "](\" + .url + ") " + .message + " (by " + .author.name + ")"' \
            | head -n 5)

          # -------------------------------
          # สร้างข้อความที่จะส่งไปยัง Discord
          # -------------------------------
          CONTENT="📢 **มีการ Push ใหม่ที่ $REPO**\nBranch: \`$BRANCH\`\nโดย: $AUTHOR\n\nCommits:\n$COMMITS"

          # ส่งแบบ suppress embeds
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$(jq -n --arg content "$CONTENT" '{content:$content, flags:4096}')" \
               "$DISCORD_WEBHOOK"

