name: Notify Discord on Push

on:
  push:   # จะทำงานทุกครั้งที่มีการ push
    branches:
      - "**"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send commit info to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          AUTHOR="${{ github.actor }}"
          REPO="${{ github.repository }}"
          BRANCH="${{ github.ref_name }}"
          COMMIT_MSG=$(echo "${{ github.event.head_commit.message }}" | jq -Rsa .)
          COMMIT_URL="${{ "github.event.head_commit.url" }}"
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)

          CONTENT="📢 **New push on $REPO**\nBranch: \`$BRANCH\`\nCommit: [$SHORT_SHA]($COMMIT_URL)\nBy: $AUTHOR\nMessage: $COMMIT_MSG"

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": $CONTENT}" \
               "$DISCORD_WEBHOOK"
